"""Coherra App Persistence Layer — Postgres (with SQLite fallback) Database for Users, Wallets & Audit History.

Manages persistent records:
  - `users`: privy_user_id (PK), email, created_at
  - `wallets`: wallet_address (PK), privy_user_id (FK), linked_at
  - `audit_history`: id (PK), privy_user_id, wallet_address, health_score, issues_found (JSON), payment_tx_hash, created_at
"""
from __future__ import annotations

import json
import os
import sqlite3
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Database Configuration & DSN
# ---------------------------------------------------------------------------

DEFAULT_APP_DB_PATH = Path(os.environ.get(
    "COHERRA_APP_DB",
    Path.home() / ".sibyl-memory" / "coherra_app.db",
))

def get_database_url() -> str | None:
    return os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL") or None

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS users (
    privy_user_id TEXT PRIMARY KEY,
    email TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS wallets (
    wallet_address TEXT PRIMARY KEY,
    privy_user_id TEXT NOT NULL REFERENCES users(privy_user_id),
    linked_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_history (
    id INTEGER PRIMARY KEY {autoincrement},
    privy_user_id TEXT NOT NULL REFERENCES users(privy_user_id),
    wallet_address TEXT,
    health_score INTEGER NOT NULL,
    issues_found TEXT NOT NULL,
    payment_tx_hash TEXT,
    created_at TEXT NOT NULL
);
"""

# ---------------------------------------------------------------------------
# Backend Implementation (SQLite & Postgres)
# ---------------------------------------------------------------------------

class _SqliteAppBackend:
    def __init__(self, db_path: Path | str | None = None) -> None:
        self._path = Path(db_path) if db_path else DEFAULT_APP_DB_PATH
        self._path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        self._lock = threading.Lock()
        self._init_schema()

    def _init_schema(self) -> None:
        ddl = _SCHEMA_SQL.replace("{autoincrement}", "AUTOINCREMENT")
        with self._lock:
            conn = sqlite3.connect(str(self._path), check_same_thread=False)
            try:
                with conn:
                    for stmt in ddl.split(";"):
                        stmt = stmt.strip()
                        if stmt:
                            conn.execute(stmt)
            finally:
                conn.close()

    def execute_query(self, sql: str, params: tuple | list = ()) -> list[dict[str, Any]]:
        with self._lock:
            conn = sqlite3.connect(str(self._path), check_same_thread=False)
            conn.row_factory = sqlite3.Row
            try:
                cur = conn.execute(sql, params)
                return [dict(r) for r in cur.fetchall()]
            finally:
                conn.close()

    def execute_write(self, sql: str, params: tuple | list = (), returning_id: bool = False) -> dict[str, Any]:
        with self._lock:
            conn = sqlite3.connect(str(self._path), check_same_thread=False)
            try:
                with conn:
                    cur = conn.execute(sql, params)
                    return {"lastrowid": cur.lastrowid, "rowcount": cur.rowcount}
            finally:
                conn.close()


class _PostgresAppBackend:
    def __init__(self, dsn: str) -> None:
        self._dsn = dsn
        self._lock = threading.Lock()
        self._init_schema()

    def _init_schema(self) -> None:
        import psycopg
        ddl = _SCHEMA_SQL.replace("{autoincrement}", "GENERATED BY DEFAULT AS IDENTITY")
        with self._lock:
            with psycopg.connect(self._dsn) as conn:
                with conn.cursor() as cur:
                    for stmt in ddl.split(";"):
                        stmt = stmt.strip()
                        if stmt:
                            cur.execute(stmt)
                conn.commit()

    def execute_query(self, sql: str, params: tuple | list = ()) -> list[dict[str, Any]]:
        import psycopg
        sql = sql.replace("?", "%s")
        with self._lock:
            with psycopg.connect(self._dsn) as conn:
                with conn.cursor() as cur:
                    cur.execute(sql, params)
                    if cur.description:
                        cols = [d.name for d in cur.description]
                        return [dict(zip(cols, row)) for row in cur.fetchall()]
                    return []

    def execute_write(self, sql: str, params: tuple | list = (), returning_id: bool = False) -> dict[str, Any]:
        import psycopg
        sql = sql.replace("?", "%s")
        if returning_id and "RETURNING" not in sql.upper():
            sql = f"{sql.rstrip(';')} RETURNING id"
        with self._lock:
            with psycopg.connect(self._dsn) as conn:
                with conn.cursor() as cur:
                    cur.execute(sql, params)
                    lastrowid = None
                    if returning_id and cur.description:
                        row = cur.fetchone()
                        if row:
                            lastrowid = row[0]
                    conn.commit()
                    return {"lastrowid": lastrowid, "rowcount": cur.rowcount}


def _get_backend(db_path: Path | str | None = None, database_url: str | None = None) -> _SqliteAppBackend | _PostgresAppBackend:
    dsn = database_url or (get_database_url() if db_path is None else None)
    if dsn and (dsn.startswith("postgres://") or dsn.startswith("postgresql://")):
        return _PostgresAppBackend(dsn)
    return _SqliteAppBackend(db_path)


def init_db(db_path: Path | str | None = None, database_url: str | None = None) -> None:
    """Initialize database tables if they do not exist."""
    _get_backend(db_path=db_path, database_url=database_url)


def _iso_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------------------
# User & Wallet CRUD
# ---------------------------------------------------------------------------

def upsert_user(
    privy_user_id: str,
    email: str | None = None,
    db_path: Path | str | None = None,
    database_url: str | None = None,
) -> dict[str, Any]:
    """Insert user if absent; update email if supplied."""
    backend = _get_backend(db_path, database_url)
    now = _iso_now()

    existing = backend.execute_query(
        "SELECT privy_user_id, email, created_at FROM users WHERE privy_user_id = ?",
        (privy_user_id,),
    )

    if existing:
        user_row = existing[0]
        if email and user_row.get("email") != email:
            backend.execute_write(
                "UPDATE users SET email = ? WHERE privy_user_id = ?",
                (email, privy_user_id),
            )
        return {
            "privy_user_id": privy_user_id,
            "email": email or user_row.get("email"),
            "created_at": user_row.get("created_at"),
        }
    else:
        backend.execute_write(
            "INSERT INTO users (privy_user_id, email, created_at) VALUES (?, ?, ?)",
            (privy_user_id, email, now),
        )
        return {
            "privy_user_id": privy_user_id,
            "email": email,
            "created_at": now,
        }


def link_wallet(
    privy_user_id: str,
    wallet_address: str,
    email: str | None = None,
    db_path: Path | str | None = None,
    database_url: str | None = None,
) -> dict[str, Any]:
    """Link a wallet address to a privy_user_id."""
    upsert_user(privy_user_id, email=email, db_path=db_path, database_url=database_url)
    wallet_address = wallet_address.lower().strip()
    now = _iso_now()
    backend = _get_backend(db_path, database_url)

    # Dialect-safe upsert for both PG and SQLite
    backend.execute_write(
        """
        INSERT INTO wallets (wallet_address, privy_user_id, linked_at)
        VALUES (?, ?, ?)
        ON CONFLICT(wallet_address) DO UPDATE SET
            privy_user_id = excluded.privy_user_id,
            linked_at = excluded.linked_at
        """,
        (wallet_address, privy_user_id, now),
    )
    return {
        "wallet_address": wallet_address,
        "privy_user_id": privy_user_id,
        "linked_at": now,
    }


# ---------------------------------------------------------------------------
# Audit History CRUD
# ---------------------------------------------------------------------------

def record_audit_history(
    privy_user_id: str,
    health_score: int,
    issues_found: list[dict[str, Any]],
    wallet_address: str | None = None,
    payment_tx_hash: str | None = None,
    db_path: Path | str | None = None,
    database_url: str | None = None,
) -> dict[str, Any]:
    """Record a completed audit run to audit_history."""
    upsert_user(privy_user_id, db_path=db_path, database_url=database_url)
    now = _iso_now()
    issues_json = json.dumps(issues_found, ensure_ascii=False)
    wallet_clean = wallet_address.lower().strip() if wallet_address else None
    backend = _get_backend(db_path, database_url)

    res = backend.execute_write(
        """
        INSERT INTO audit_history
        (privy_user_id, wallet_address, health_score, issues_found, payment_tx_hash, created_at)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (privy_user_id, wallet_clean, health_score, issues_json, payment_tx_hash, now),
        returning_id=True,
    )
    row_id = res.get("lastrowid")
    return {
        "id": row_id,
        "privy_user_id": privy_user_id,
        "wallet_address": wallet_clean,
        "health_score": health_score,
        "issues_found": issues_found,
        "payment_tx_hash": payment_tx_hash,
        "created_at": now,
    }


def get_audit_history(
    privy_user_id: str,
    limit: int = 20,
    db_path: Path | str | None = None,
    database_url: str | None = None,
) -> list[dict[str, Any]]:
    """Fetch past audits for a given privy_user_id, most recent first."""
    backend = _get_backend(db_path, database_url)
    rows = backend.execute_query(
        """
        SELECT id, privy_user_id, wallet_address, health_score, issues_found, payment_tx_hash, created_at
        FROM audit_history
        WHERE privy_user_id = ?
        ORDER BY id DESC
        LIMIT ?
        """,
        (privy_user_id, max(1, min(limit, 100))),
    )

    history = []
    for r in rows:
        try:
            issues = json.loads(r["issues_found"])
        except Exception:
            issues = []
        history.append({
            "id": r.get("id"),
            "privy_user_id": r.get("privy_user_id"),
            "wallet_address": r.get("wallet_address"),
            "health_score": r.get("health_score"),
            "issues_found": issues,
            "payment_tx_hash": r.get("payment_tx_hash"),
            "created_at": r.get("created_at"),
        })
    return history

